version: "3.7"
services:
  flask_server:
    container_name: flask_server
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - .:/flask_server
    depends_on:
      - tf_serving
    networks:
      flask-network:
        aliases:
          - flask_server

  tf_serving:
    container_name: tf_serving
    build:
      context: ./tf_serving
      dockerfile: Dockerfile
    ports:
        - 8500:8500
        - 8501:8501
    volumes:
        - ./tf_serving/models:/models
        - ./tf_serving/serving_docker.config:/models/serving_docker.config
    networks:
      - flask-network

networks:
  flask-network:
