version: "3.7"
services:
  flask_app:
    container_name: flask_app
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    volumes:
      - ./flask_app:/flask_app
    depends_on:
      - tf_serving
    networks:
      flask-network:
        aliases:
          - flask_app

  tf_serving:
    container_name: tf_serving
    build:
      context: ./tf_serving
      dockerfile: Dockerfile
    ports:
        - "8500"
        - "8501"
    volumes:
        - ./tf_serving/models:/models
    networks:
      - flask-network

networks:
  flask-network:
