LABELS = {'Abyssinian': 0,
          'Balinese': 1,
          'Bengal': 2,
          'Birman': 3,
          'Bombay': 4,
          'Burmese': 5,
          'Burmilla': 6,
          'Calico': 7,
          'Chartreux': 8,
          'Chausie': 9,
          'Cornish rex': 10,
          'Devon rex': 11,
          'Egyptian mau': 12,
          'Havana': 13,
          'Himalayan': 14,
          'Korat': 15,
          'Maine coon': 16,
          'Munchkin': 17,
          'Norwegian forest cat': 18,
          'Ocicat': 19,
          'Persian': 20,
          'Pixiebob': 21,
          'Ragdoll': 22,
          'Russian blue': 23,
          'Scottish fold': 24,
          'Selkirk rex': 25,
          'Siamese': 26,
          'Siberian': 27,
          'Singapura': 28,
          'Snowshoe': 29,
          'Somali': 30,
          'Sphynx': 31,
          'Tabby': 32,
          'Torbie': 33,
          'Tortoiseshell': 34,
          'Turkish angora': 35,
          'Tuxedo': 36
          }

BREEDS = list(LABELS.keys())
