LABELS = {'abyssinian': 0,
          'balinese': 1,
          'bengal': 2,
          'birman': 3,
          'bombay': 4,
          'burmese': 5,
          'burmilla': 6,
          'calico': 7,
          'chartreux': 8,
          'chausie': 9,
          'cornish rex': 10,
          'devon rex': 11,
          'egyptian mau': 12,
          'havana': 13,
          'himalayan': 14,
          'korat': 15,
          'maine coon': 16,
          'munchkin': 17,
          'norwegian forest cat': 18,
          'ocicat': 19,
          'persian': 20,
          'pixiebob': 21,
          'ragdoll': 22,
          'russian blue': 23,
          'scottish fold': 24,
          'selkirk rex': 25,
          'siamese': 26,
          'siberian': 27,
          'singapura': 28,
          'snowshoe': 29,
          'somali': 30,
          'sphynx': 31,
          'tabby': 32,
          'torbie': 33,
          'tortoiseshell': 34,
          'turkish angora': 35,
          'tuxedo': 36
          }

BREEDS = list(LABELS.keys())